# Generated by Django 4.0.3 on 2023-06-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgv', '0002_movie_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_path',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='item_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movies',
        ),
    ]
